### ISSUE TITLE
printf() acting weird

### ISSUE THREAD

**Issue by fxrobin** [freemint/libcmini#102]
When I'm using `printf("some string\n");`
The next string won't appear at the first char on the next line.
I have to use `printf("\r\n");` in order to work perfectly.

My code about this issue is here : 
https://www.fxjavadevblog.fr/atari-st-4-bitplanes/#mise-en-pratique-en-c

**Comment by rosenrost** [comment]
To solve this problem, you have to compile the library with `-DSTDIO_MAP_NEWLINE`.

**Comment by fxrobin** [comment]
Thanx a lot!
Should it be the default behaviour?

**Comment by rosenrost** [comment]
In my opinion, it should. Mapping "\n" to "\r\n" has been implemented last summer and we had a discussion about making it the default behaviour. This ended up in leaving the default as it was before and make the mapping optional.

**Comment by rosenrost** [comment]
To make it easier, you can create a file `Make.config.local` with the following content:

```
CFLAGS = -DSTDIO_MAP_NEWLINE
```

**Comment by fxrobin** [comment]
Thanx
