### ISSUE TITLE
Stat() st_(a|c|m)time members ignore date part of _DTA.

### ISSUE THREAD

**Issue by codesmythe** [freemint/libcmini#108]
When stat() sets the st_atime, st_ctime, and st_mtime members of the stat struct, it uses only the dta_time part of the _DTA created by the call to FsFirst() and ignores the dta_date part. 

https://github.com/freemint/libcmini/blob/master/sources/stat.c#L37

The fstat() function handles this correctly.

**Comment by mfro0** [comment]
closed with #109 
Thank you!
