### ISSUE TITLE
getopt() doesn't handle option arguments correctly

### ISSUE THREAD

**Issue by codesmythe** [freemint/libcmini#111]
The getopt() standard function allows options to have arguments if the option is followed by a colon in the option string. Libcmini doesn't seem to handle this correctly. 

Here's a bit sample code:

```
#include <getopt.h>
#include <stdio.h>

int main(int argc, char **argv)
{
     const char *optstring = "abc:def:gh";
     char ch;
     while ((ch = getopt(argc, argv, optstring)) != -1) { 
         if (optarg) printf("ch = '%c', optarg = '%s'\r\n", ch, optarg);
         else printf("ch = '%c'\r\n", ch);
         if (ch == '?') break;
     }
     return 0;
}
```

Here is the output on my Mac running Ventura:
```
% gcc -Wall -Werror -o getopt_test getopt_test.c
% ./getopt_test -a -b -ctest -d -e -f test2
ch = 'a'
ch = 'b'
ch = 'c', optarg = 'test'
ch = 'd'
ch = 'e'
ch = 'f', optarg = 'test2'
```

Here is the output when compiling with libcmini, running on Hatari under EmuTOS:

<img width="346" alt="Screenshot 2023-02-18 at 10 54 43 AM" src="https://user-images.githubusercontent.com/1444655/219878159-c39d60b7-6103-45a3-bc62-3859b617d09b.png">

If I separate the -c option's argument with whitespace, here is the output:

<img width="404" alt="Screenshot 2023-02-18 at 10 56 11 AM" src="https://user-images.githubusercontent.com/1444655/219878213-983efefb-cba1-478d-a45e-869119381c2b.png">

Thanks.

**Comment by mfro0** [comment]
fixed with 9dd8a01
