### ISSUE TITLE
Feature request: libcmini should be compilable with the new mintelf toolchain

### ISSUE THREAD

**Issue by mikrosk** [freemint/libcmini#117]
The title says it all. As it doesn't use inline assembly that much, it shouldn't be too complex.

**Comment by benjihan** [comment]
I have a compiled version of the mintelf toolchain with libcmini as its companion libc. I did not test it extensively. I might have patch a few things here ans there to build it.

**Comment by mikrosk** [comment]
That would be most welcome! :)

**Comment by benjihan** [comment]
Trying to find what I did.
I have a very simple compile script that compiles libcmini successfully.
```
#! /bin/bash -e

cd -- $(dirname "$0")

install_dir="$HOME/Arch/libcmini-mintelf"

cflags=( -Wall -Wstrict-prototypes -Wmissing-prototypes
-Wdeclaration-after-statement -Werror -Os -fomit-frame-pointer
'$(REGPREFIX)' )

exec make \
     VERBOSE=yes \
     PREFIX="${install_dir}" \
     CROSSBINDIR=m68k-atari-mintelf- \
     CROSSPREFIX=m68k-atari-mintelf- \
     CC=m68k-atari-mintelf-gcc \
     MYCFLAGS="${cflags[*]}" \
     \
     "$@"  
```

**Comment by benjihan** [comment]
Missing the Make.config.local
```
# -*- makefile -*-

REGPREFIX=-Wa,--register-prefix-optional

CFLAGS = $(MYCFLAGS)

$(foreach D,. mshort m5475 m5475/mshort m68020-60 m68020-60/mshort,$(foreach F, getopt vfprintf, build/$D/objs/$F.o)) : REGPREFIX=

```

**Comment by mikrosk** [comment]
That's some hardcore makefileing there. :) I hope @mfro0 will find some time to make a proper patch.

**Comment by benjihan** [comment]
Basically it removes `-Wa,--register-prefix-optional` when compiling  getopt.c and vfprintf.c
It's extremely simple to patch there are C variables using register reserved names (namely `fp` and `sp``) in these 2 files.
The rest is just compiler selection and settings which is a bit of a hassle because of the recursive usage of make.

**Comment by th-otto** [comment]
I'm too lazy to make up a PR, but attached is a patch that should address this. Maybe @mfro0 can have a look?

It should also fix a few issues for the FASTCALL cases (fastcall passes/returns doubles in FPU registers for -m68881)

[fastcall.patch.txt](https://github.com/freemint/libcmini/files/15136998/fastcall.patch.txt)

**Comment by mikrosk** [comment]
There you go: #122. ;)
