### ISSUE TITLE
Linker complains: undefined reference to `_atexit'

### ISSUE THREAD

**Issue by rosenrost** [freemint/libcmini#126]
Anything must have changed recently to make the linker compain about an undefined reference to _atexit. This happens only when atexit() is not explicitly used within the program. After adding such a call, everything gets built fine (see examples below).

Everything worked fine up to my changes from February 5 (397b1bd). Today I synced my fork to include @th-otto's commits and ran into this issue. I neither use -mfastcall nor ELF libraries.

Example 1 without calling atexit():
```
#include <stdio.h>
int main()
{
    puts("Hello world!");
    return 0;
}
```
```
$ make
m68k-atari-mint-gcc.exe -x c -std=c99 -Wall -nostdlib -nodefaultlibs -I/usr/local/lib/libcmini/include -O2 -c main.c -o main.o
m68k-atari-mint-gcc.exe /usr/local/lib/libcmini/lib/crt0.o -o test.tos main.o -s -nostdlib -nodefaultlibs -L/usr/local/lib/libcmini/lib -lcmini -lgcc
/opt/cross-mint/lib/gcc/m68k-atari-mint/4.6.4/libgcc.a(__main.o):__main.o:(.text+0x56): undefined reference to `_atexit'
collect2: ld returned 1 exit status
make: *** [Makefile:49: test.tos] Fehler 1

$
```
Example 2 with calling atexit():
```
#include <stdio.h>
#include <stdlib.h>
static void exitfunc(void)
{
    puts("Bye.");
}
int main()
{
    atexit(exitfunc);
    puts("Hello world!");
    return 0;
}
```
```
$ make
m68k-atari-mint-gcc.exe -x c -std=c99 -Wall -nostdlib -nodefaultlibs -I/usr/local/lib/libcmini/include -O2 -c main.c -o main.o
m68k-atari-mint-gcc.exe /usr/local/lib/libcmini/lib/crt0.o -o test.tos main.o -s -nostdlib -nodefaultlibs -L/usr/local/lib/libcmini/lib -lcmini -lgcc

$
```
This is my Make.config.local:
```
ONLY_68K=Y
CFLAGS  =-Werror -O2 -fomit-frame-pointer -DSTDIO_MAP_NEWLINE
PREFIX  =/usr/local/lib/libcmini
```

**Comment by th-otto** [comment]
On Dienstag, 11. Juni 2024 11:46:41 CEST Oliver wrote:
> -L/usr/local/lib/libcmini/lib -lcmini -lgcc

You have to change the sequence to -lgcc -lcmini -lgcc

libgcc.a has the reference to atexit().
(that should have always been the case, dunno why it worked before)

Alternatively, if you are sure that your program does not need global 
constructors, you can provide a dummy __main() function so save some bytes. 
That applies to both a.out and elf toolchains.

**Comment by rosenrost** [comment]
Your suggested change really solves the issue, thanks a lot. That should be added to README.md.
