### ISSUE TITLE
Help wanted: unexpected realloc() failure

### ISSUE THREAD

**Issue by rosenrost** [freemint/libcmini#93]
When I compile a large application against libcmini, I run into an unexpected failure when calling realloc(). This didn't happen with the previous version, so I am a little bit confused.

realloc() returns a NULL pointer and sets errno to EINVAL:

realloc.c (lines 29-33):
```
	if (p->valid != VAL_ALLOC)
	{
		errno = EINVAL;
		return NULL;
	}
```
Under which circumstances can this happen?

I changed the source of my application to log every call to malloc(), calloc(), realloc(), free(), str[n]dup() and [v]asprintf(). You find it attached at the bottom of this post, maybe it can help. The number after the hash sign is the consecutive number of the call to the function. In the last line you can see the call to realloc() which returns the NULL pointer. My application performs a system reset whenever memory allocation fails.

[Log file](https://github.com/freemint/libcmini/files/4567984/log.txt)

**Comment by th-otto** [comment]
Typically that happens when either free the same memory twice, or pass a pointer that was not returned from malloc().
Taking a short look at your log it could also be that you wrote past the string returned just before the realloc call.

**Comment by rosenrost** [comment]
Writing past the string was the problem. It's a consequential issue caused by #94.
