### ISSUE TITLE
doprnt() doesn't take account of precision when formatting integers (d, i, u, x, X, o)

### ISSUE THREAD

**Issue by rosenrost** [freemint/libcmini#99]
This leads to wrong results when using a format string like `%.4d`.

Some examples:

```
          VAL=4     VAL=-4

"%.4d"
EXPECTED  "0004"    "-0004"
RESULT    "4"	    "-4"

"%6.4d"
EXPECTED  "  0004"  " -0004"
RESULT    "     4"  "    -4"

"%-.4d"
EXPECTED  "0004"    "-0004"
RESULT    "4"	    "-4"

"%-6.4d"
EXPECTED  "0004  "  "-0004 "
RESULT    "4     "  "-4    "
```

**Comment by mfro0** [comment]
Thanks for your patch!

**Comment by rosenrost** [comment]
I will add my test programme shortly. It creates (hopefully) all possible modifier combinations and several values for field width and precision for a set of numbers including negatives and 0. The output is written to a file which then can be diffed to the output of the same programme compiled in an environment known to be working correctly (I did it in my Cygwin environment).
